# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=256)),
                ('job_title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.CharField(choices=[('effectiveness', 'Effectiveness'), ('speed', 'Speed'), ('communication', 'Communication'), ('organization', 'Organization'), ('reliability', 'Reliability')], max_length=128)),
                ('reviews', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('description', models.CharField(max_length=256)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeInfo')),
                ('reviewer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reviewer.ReviewerInfo')),
            ],
        ),
    ]
